# Generated by Django 3.1.5 on 2021-01-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=None, null=True, upload_to='images', verbose_name='Photo'),
        ),
    ]
