# Generated by Django 3.1.5 on 2021-01-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_articles_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.TextField(blank=True, null=True, verbose_name='Автор комментария'),
        ),
    ]
