# Generated by Django 3.1.5 on 2021-01-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210118_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
    ]
