# Generated by Django 3.1.5 on 2021-01-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_comments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.TextField(blank=True, null=True, verbose_name='Автор комментария'),
        ),
    ]
