# Generated by Django 3.1.5 on 2021-01-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210119_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='create_date_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='create_date_kz',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='create_date_ru',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='articles',
            name='text_kz',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='articles',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='comments',
            name='create_date_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='create_date_kz',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='create_date_ru',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст комментария'),
        ),
        migrations.AddField(
            model_name='comments',
            name='text_kz',
            field=models.TextField(null=True, verbose_name='Текст комментария'),
        ),
        migrations.AddField(
            model_name='comments',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст комментария'),
        ),
    ]
