# Generated by Django 3.1.5 on 2021-01-20 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210119_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='create_date_en',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='create_date_kz',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='create_date_ru',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='create_date_en',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='create_date_kz',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='create_date_ru',
        ),
    ]
