# Generated by Django 3.1.5 on 2021-01-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210120_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='text_kz',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='text_ru',
        ),
        migrations.AddField(
            model_name='articles',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='articles',
            name='name_kz',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='articles',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
