# Generated by Django 3.1.5 on 2021-02-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210120_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='avtor',
            field=models.CharField(max_length=200, null=True, verbose_name='Автор статьи'),
        ),
        migrations.AddField(
            model_name='articles',
            name='email',
            field=models.EmailField(max_length=120, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='articles',
            name='ok',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AddField(
            model_name='articles',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='Telephone'),
        ),
    ]
