# Generated by Django 3.1.5 on 2021-02-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210209_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='user_name',
            field=models.CharField(max_length=200, null=True, verbose_name='имя'),
        ),
    ]
