# Generated by Django 3.1.5 on 2021-02-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_articles_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='user_firstname',
            field=models.CharField(max_length=200, null=True, verbose_name='фамилия'),
        ),
    ]
