# Generated by Django 3.1.5 on 2021-02-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_articles_user_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_photo',
            field=models.CharField(max_length=200, null=True, verbose_name='фото'),
        ),
    ]
