# Generated by Django 3.1.5 on 2021-02-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_articles_avtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_firstname',
            field=models.CharField(max_length=200, null=True, verbose_name='фамилия'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_name',
            field=models.CharField(max_length=200, null=True, verbose_name='имя'),
        ),
    ]
