# Generated by Django 3.1.5 on 2021-02-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_articles_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='document',
            field=models.FileField(default=None, upload_to='static/'),
        ),
    ]
