# Generated by Django 3.1.5 on 2021-02-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210218_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='document',
            field=models.FileField(default=None, upload_to='static/docs/'),
        ),
    ]
