# Generated by Django 3.1.5 on 2021-03-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210329_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='docs2',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='filename',
        ),
    ]
