# Generated by Django 3.1.5 on 2021-04-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210329_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='docs',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='image',
        ),
        migrations.AddField(
            model_name='articles',
            name='document',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='state',
            field=models.CharField(max_length=200, null=True, verbose_name='документы'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
