# Generated by Django 3.1.5 on 2021-04-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_articles_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='state',
        ),
    ]
