# Generated by Django 3.1.5 on 2021-04-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_articles_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='state',
            field=models.CharField(max_length=200, null=True, verbose_name='документы'),
        ),
    ]
