# Generated by Django 3.1.5 on 2021-05-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210518_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='email',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='phone',
        ),
        migrations.AddField(
            model_name='articles',
            name='price',
            field=models.CharField(max_length=120, null=True, verbose_name='email'),
        ),
    ]
