# Generated by Django 3.1.5 on 2021-05-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_zayavka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Услуга'),
        ),
    ]
