# Generated by Django 3.1.5 on 2021-02-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text1', models.TextField(blank=True, verbose_name='Текст1')),
                ('text2', models.TextField(blank=True, verbose_name='Текст2')),
                ('text3', models.TextField(blank=True, verbose_name='Текст3')),
                ('image', models.ImageField(blank=None, null=True, upload_to='images/', verbose_name='Изображение')),
                ('image2', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение 2')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
